AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for running Kittens Carousel Static Website
  on EC2. Kittens Carousel Static Website will be deployed on Amazon Linux 2 
  (ami-02e136e904f3da870) custom security group which allows 
  http connections on port 80 and ssh port 22 from anywhere. Kittens Carousel Static
  Websiteis downloaded from my Public Github repository, then deployed on 
  Apache Web Server.

Resources:
  securityGroupKittens:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP & SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0022f774911c1d690
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroupIds:
        - !Ref securityGroupKittens
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          yum install git -y
          cd /var/www/html
          git clone https://github.com/John-Daunt/my-projects.git
          mv my-projects/aws/projects/Project-101-kittens-carousel-static-website-ec2/static-web/* .
          rm -rf my-projects
          systemctl start httpd
          systemctl enable httpd

Outputs:
  WebServerDNSName:
    Description: The DNSName of the Apache Web Server
    Value: !GetAtt WebServerHost.PublicDnsName
